[greeter]
background=/usr/share/greenwayos/ctos/wallpaper-lock.png
theme-name=GreenWay-ctOS
icon-theme-name=Adwaita
font-name=JetBrains Mono 11
xft-antialias=true
xft-dpi=96
indicators=~host;~spacer;~clock;~spacer;~session;~power
clock-format=%H:%M // %Y-%m-%d
user-background=false
hide-user-image=true
